name: Import Publications From Bibtex

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: ['main']
    paths: ['**/publications.bib']
  workflow_dispatch:

jobs:
  hugoblox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install academic-file-converter
        run: |
          python -m pip install --upgrade pip
          pip install academic-file-converter

      - name: Run Academic File Converter
        if: ${{ hashFiles('**/publications.bib') != '' }}
        run: academic import data/publications.bib -o content/publication/ --compact

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'content: import publications from Bibtex'
          title: Hugo Blox Builder - Import latest publications
          body: |
            Import the latest publications from `publications.bib` to `content/publication/`.
            将最新的出版物从`publications.bib`导入到`content/publication/`。
            [View Documentation](https://github.com/GetRD/academic-file-converter)
          base: main
          labels: automated-pr, content
          branch: hugoblox-import-publications
          delete-branch: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
